export const navItems = [
  { to: "/admin/approvals", label: "Approvals", roles: ["admin"] },
  { to: "/my-enrollments", label: "My Enrollments", roles: ["student"] },
  { to: "/courses", label: "Courses", roles: ["admin", "professor"] },
  { to: "/students", label: "Students", roles: ["admin", "professor"] },
  { to: "/professors", label: "Professors", roles: ["admin"] },
  { to: "/semesters", label: "Semesters", roles: ["admin"] },
  { to: "/departments", label: "Departments", roles: ["admin"] },
  { to: "/schedules", label: "Schedules", roles: ["admin", "professor"] },
  { to: "/enrollments", label: "Enrollments", roles: ["admin"] },
  { to: "/enrollments", label: "Course Enrollments", roles: ["professor"] },
  { to: "/payments", label: "Payments", roles: ["admin"] },
  { to: "/revenue", label: "Revenue", roles: ["admin"] },
  { to: "/materials", label: "Materials", roles: ["professor", "student"] },
  { to: "/waiting-list", label: "Waiting List", roles: ["admin", "professor", "student"] },
  { to: "/announcements", label: "Announcements", roles: ["admin", "professor", "student"] },
];
